// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHx0w_MTC_ca-qFmZ7bB6tJb8nXwy6OSM',
    appId: '1:67589910477:web:459dd432479fea44271e84',
    messagingSenderId: '67589910477',
    projectId: 'perdiz-adv',
    authDomain: 'perdiz-adv.firebaseapp.com',
    storageBucket: 'perdiz-adv.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn51szJoHtCf_yALXkx7wW9Z2Z-2Og8Sw',
    appId: '1:67589910477:android:ed2b7ab30df6611d271e84',
    messagingSenderId: '67589910477',
    projectId: 'perdiz-adv',
    storageBucket: 'perdiz-adv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwy2bly9E6jotjRsUZSXifcim-q9XcgZQ',
    appId: '1:67589910477:ios:2401162052912aae271e84',
    messagingSenderId: '67589910477',
    projectId: 'perdiz-adv',
    storageBucket: 'perdiz-adv.appspot.com',
    iosClientId: '67589910477-pt22vc5vshd7jk50gocld2ebt5i9crmc.apps.googleusercontent.com',
    iosBundleId: 'com.example.perdiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwy2bly9E6jotjRsUZSXifcim-q9XcgZQ',
    appId: '1:67589910477:ios:2401162052912aae271e84',
    messagingSenderId: '67589910477',
    projectId: 'perdiz-adv',
    storageBucket: 'perdiz-adv.appspot.com',
    iosClientId: '67589910477-pt22vc5vshd7jk50gocld2ebt5i9crmc.apps.googleusercontent.com',
    iosBundleId: 'com.example.perdiz',
  );
}
